version: '3.5'

services:

  app:
    build: .
    container_name: nestjs-rate-limiter-challenge
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ".:/usr/src/app/"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  mongo:
    image: mongo:4.2.8
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "mongo:/data/db"

volumes:
  mongo:
